### ISSUE TITLE
Make download HQ and HI-FI quality available

### ISSUE THREAD

**Issue by rarealphacat** [jaris58/joox_dl#11]
Options are available for VIP (subscribed) to download HQ and HI-FI quality. Can you add the -hq download to check for highest available quality instead of fixed 320kbps? e.g. HI-FI has 1411kbps for some songs

**Comment by jaris58** [comment]
Hi, can you tell me what key are used to get size of HI-FI ? because I only have account non premium which HI-FI key / column not show in response from server.

**Comment by jaris58** [comment]
> Options are available for VIP (subscribed) to download HQ and HI-FI quality. Can you add the -hq download to check for highest available quality instead of fixed 320kbps? e.g. HI-FI has 1411kbps for some songs

Hi, can you tell me what key are used to get size of HI-FI ? because I only have account non premium which HI-FI key / column not show in response from server.

**Comment by rarealphacat** [comment]
I'm unable to get the key from my phone and it appears web platform does not support Hi-Fi option (I'm on linux). Joox is, however, giving out free VIP access to new account after 30 mins of playtime if you can find the key from there.

**Comment by jaris58** [comment]
> I'm unable to get the key from my phone and it appears web platform does not support Hi-Fi option (I'm on linux). Joox is, however, giving out free VIP access to new account after 30 mins of playtime if you can find the key from there.

I have try register new account in joox but free VIP access not available.

**Comment by rarealphacat** [comment]
try VPN to Hong Kong? It's where I get VIP access for free everyday just by listening with Joox

**Comment by jaris58** [comment]
I have tried login with VIP account there in no different from existing its only have 4 file song 2 MP3 [128 bit and 320 bit]  then 2 M4A [96 bit and 192]
