### ISSUE TITLE
Bitrate Quality

### ISSUE THREAD

**Issue by Adhitore** [jaris58/joox_dl#6]
Bitrate di -hq kok cma sampai 192kbps ya? 
![Screen Shot 2021-04-08 at 14 51 31](https://user-images.githubusercontent.com/39517736/113988700-ed062600-9879-11eb-9a10-958f244e2e7a.png)

**Comment by jaris58** [comment]
Untuk bitrate:
MP3 = 128 kbps
MP3 HQ = 320 kbps
M4A = 96 kbps
M4A HQ = 192 kbps

**Comment by rarealphacat** [comment]
any plans to make download HQ and HI-FI quality available?
